module.exports = Object.freeze({
  LINK_ACCEPTED: 'LINK_ACCEPTED',
  LINK_ENDED: 'LINK_ENDED',
  LINK_REJECTED: 'LINK_REJECTED',
  LINK_REQUESTED: 'LINK_REQUESTED',
  PROFESSIONAL_APPROVED: 'PROFESSIONAL_APPROVED',
  PROFESSIONAL_REGISTERED: 'PROFESSIONAL_REGISTERED',
  PROFESSIONAL_REJECTED: 'PROFESSIONAL_REJECTED',
  PROTOCOL_CREATED: 'PROTOCOL_CREATED',
  PROTOCOL_STATUS_CHANGED: 'PROTOCOL_STATUS_CHANGED',
  PROTOCOL_VERSION_CREATED: 'PROTOCOL_VERSION_CREATED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',
});
